USE [master]
GO
/****** Object:  Database [FinanceManager]    Script Date: 28.05.2026 11:53:53 ******/
CREATE DATABASE [FinanceManager]
GO
ALTER DATABASE [FinanceManager] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FinanceManager].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FinanceManager] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FinanceManager] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FinanceManager] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FinanceManager] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FinanceManager] SET ARITHABORT OFF 
GO
ALTER DATABASE [FinanceManager] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FinanceManager] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FinanceManager] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FinanceManager] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FinanceManager] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FinanceManager] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FinanceManager] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FinanceManager] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FinanceManager] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FinanceManager] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FinanceManager] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FinanceManager] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FinanceManager] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FinanceManager] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FinanceManager] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FinanceManager] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FinanceManager] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FinanceManager] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FinanceManager] SET  MULTI_USER 
GO
ALTER DATABASE [FinanceManager] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FinanceManager] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FinanceManager] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FinanceManager] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FinanceManager] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FinanceManager] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FinanceManager] SET QUERY_STORE = ON
GO
ALTER DATABASE [FinanceManager] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FinanceManager]
GO
/****** Object:  Table [dbo].[Budget]    Script Date: 28.05.2026 11:53:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Budget](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[CategoryId] [int] NOT NULL,
	[Year] [int] NOT NULL,
	[Month] [tinyint] NOT NULL,
	[PlannedAmount] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_Budget] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Budget_User_Category_Period] UNIQUE NONCLUSTERED 
(
	[UserId] ASC,
	[CategoryId] ASC,
	[Year] ASC,
	[Month] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 28.05.2026 11:53:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Type] [nvarchar](10) NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transaction]    Script Date: 28.05.2026 11:53:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transaction](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[CategoryId] [int] NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[Note] [nvarchar](500) NULL,
 CONSTRAINT [PK_Transaction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 28.05.2026 11:53:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](100) NOT NULL,
	[Type] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Budget_User_Year_Month]    Script Date: 28.05.2026 11:53:53 ******/
CREATE NONCLUSTERED INDEX [IX_Budget_User_Year_Month] ON [dbo].[Budget]
(
	[UserId] ASC,
	[Year] ASC,
	[Month] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ_Category_User_Name]    Script Date: 28.05.2026 11:53:53 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UQ_Category_User_Name] ON [dbo].[Category]
(
	[UserId] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Transaction_Category]    Script Date: 28.05.2026 11:53:53 ******/
CREATE NONCLUSTERED INDEX [IX_Transaction_Category] ON [dbo].[Transaction]
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Transaction_Date_User]    Script Date: 28.05.2026 11:53:53 ******/
CREATE NONCLUSTERED INDEX [IX_Transaction_Date_User] ON [dbo].[Transaction]
(
	[Date] DESC,
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Budget]  WITH CHECK ADD  CONSTRAINT [FK_Budget_Category] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Budget] CHECK CONSTRAINT [FK_Budget_Category]
GO
ALTER TABLE [dbo].[Budget]  WITH CHECK ADD  CONSTRAINT [FK_Budget_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Budget] CHECK CONSTRAINT [FK_Budget_User]
GO
ALTER TABLE [dbo].[Category]  WITH CHECK ADD  CONSTRAINT [FK_Category_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[Category] CHECK CONSTRAINT [FK_Category_User]
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Transaction_Category] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Transaction] CHECK CONSTRAINT [FK_Transaction_Category]
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD  CONSTRAINT [FK_Transaction_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Transaction] CHECK CONSTRAINT [FK_Transaction_User]
GO
ALTER TABLE [dbo].[Budget]  WITH CHECK ADD  CONSTRAINT [CK_Budget_Month] CHECK  (([Month]>=(1) AND [Month]<=(12)))
GO
ALTER TABLE [dbo].[Budget] CHECK CONSTRAINT [CK_Budget_Month]
GO
ALTER TABLE [dbo].[Budget]  WITH CHECK ADD  CONSTRAINT [CK_Budget_PlannedAmount] CHECK  (([PlannedAmount]>(0)))
GO
ALTER TABLE [dbo].[Budget] CHECK CONSTRAINT [CK_Budget_PlannedAmount]
GO
ALTER TABLE [dbo].[Category]  WITH CHECK ADD  CONSTRAINT [CK_Category_Type] CHECK  (([Type]='Expense' OR [Type]='Income'))
GO
ALTER TABLE [dbo].[Category] CHECK CONSTRAINT [CK_Category_Type]
GO
ALTER TABLE [dbo].[Transaction]  WITH CHECK ADD  CONSTRAINT [CK_Transaction_Amount] CHECK  (([Amount]>(0)))
GO
ALTER TABLE [dbo].[Transaction] CHECK CONSTRAINT [CK_Transaction_Amount]
GO
USE [master]
GO
ALTER DATABASE [FinanceManager] SET  READ_WRITE 
GO
